In [2]:
import numpy as np

my_list = [x * 10 for x in range(1, 11)]

list = np.array(my_list).reshape(5, 2)
print(list)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [ ]:
rng = np.random.default_rng(12345)
ArrayList = rng.random(9).reshape(3, 3)
print(ArrayList)

[[0.22733602 0.31675834 0.79736546]
 [0.67625467 0.39110955 0.33281393]
 [0.59830875 0.18673419 0.67275604]]
