In [ ]:
import numpy as np

In [ ]:
integer_array = np.arange(12)
integer_array
integer_array[2]
integer_array[:5]
integer_array[::2]
new_array = integer_array.reshape(3, 4)
new_array[:,:]
new_array[1:, :]
new_array[:, 3]

In [9]:
rng = np.random.default_rng(12345)
ArrayList = rng.random(9).reshape(3, 3)
print(ArrayList)

[[0.22733602 0.31675834 0.79736546]
 [0.67625467 0.39110955 0.33281393]
 [0.59830875 0.18673419 0.67275604]]


In [ ]:
ArrayList[:2, :] # First two rows

array([[0.22733602, 0.31675834, 0.79736546],
       [0.67625467, 0.39110955, 0.33281393]])

In [ ]:
ArrayList[:, 0] # First column 

array([0.22733602, 0.67625467, 0.59830875])

In [ ]:
ArrayList[2, 1] # second number in third row

np.float64(0.18673418560371335)