# NumPy Practice Exercises

Grouped by the skills from your `1.numpy` notebooks. Everything follows one story — a small corner store called **Corner Store Pty Ltd** that wants to track its data with NumPy.

Work through the exercises **in order** — later exercises reuse arrays you create in earlier ones. No data files needed, just run the setup cell below first.

In [1]:
import numpy as np

## Exercise 1 — Creating Arrays & Random Numbers
*(covers: arrayBasics, randomNumber)*

1. Create a numpy array called `daily_sales` from the list below.
2. Print its `ndim`, `shape`, `size`, and `dtype`.
3. Reshape `daily_sales` into a 2×5 array called `sales_by_week` (2 weeks × 5 weekdays) — don't overwrite `daily_sales`, save it as a new variable.
4. Create a random generator with `np.random.default_rng(42)`, then use `rng.integers(10, 81, 12)` to get 12 random stock counts. Reshape them into a 3×4 array called `stock_grid` (3 shelves × 4 products each).

In [13]:
# Given data
daily_sales_list = [120, 95, 200, 150, 80, 60, 175, 210, 90, 130]

# 1. Create a numpy array called `daily_sales` from daily_sales_list
daily_sales = np.array(daily_sales_list)

# 2. Print ndim, shape, size, and dtype of daily_sales
daily_sales.ndim
daily_sales.shape
daily_sales.size
daily_sales.dtype
# 3. Reshape daily_sales into a 2x5 array called sales_by_week
sales_by_week = daily_sales.reshape(2, 5)

# 4. Create rng = np.random.default_rng(42), generate 12 random ints (10-80) with rng.integers(10, 81, 12),
#    then reshape into a 3x4 array called stock_grid
rng = np.random.default_rng(42)
stock_grid = rng.integers(10, 81, 12).reshape(3, 4)
stock_grid

array([[16, 64, 56, 41],
       [40, 70, 16, 59],
       [24, 16, 47, 79]])

## Exercise 2 — Indexing, Slicing & Filtering
*(covers: indexingAndSlicing, filteringArray)*

Using `stock_grid` from Exercise 1:

1. Get the full row of stock counts for shelf 2 (row index 1).
2. Get the stock counts for product column 0 across all shelves.
3. Get the single value for shelf 1 (row 0), product 3 (column 2).
4. Use a boolean mask to pull out every stock count below 25 ("low stock").
5. Use `np.where()` to build a same-shaped array called `stock_status` showing `"low"` where stock < 25, and `"ok"` everywhere else.

In [20]:
# 1. Full row for shelf 2 (row index 1)
stock_grid[1]

# 2. Column 0 across all shelves
stock_grid[:, 0]

# 3. Single value: shelf 1 (row 0), product 3 (column 2)
stock_grid[0, 2]

# 4. Boolean mask: stock counts below 25
stock_grid[stock_grid < 25]

# 5. np.where() to build stock_status ("low" / "ok")
stock_status = np.where(stock_grid < 25, "low", "ok")
stock_status

array([['low', 'ok', 'ok', 'ok'],
       ['ok', 'ok', 'low', 'ok'],
       ['low', 'low', 'ok', 'ok']], dtype='<U3')

## Exercise 3 — Array Operations & Broadcasting
*(covers: arrayOperations, broadcasting)*

1. Create `prices = np.array([3.50, 12.00, 7.25, 1.80, 25.00, 9.99])`.
2. Add a flat $2 delivery surcharge to every price using broadcasting → store as `prices_with_delivery`.
3. Create `stock = np.array([40, 15, 60, 100, 8, 33])` (matching order to `prices`).
4. Calculate the total value of stock on hand for each product (`prices * stock`) → store as `stock_value`.
5. Apply a storewide 20% discount to `prices` (multiply by 0.8) and round to 2 decimals → store as `discounted_prices`.

In [ ]:
prices = np.array([3.50, 12.00, 7.25, 1.80, 25.00, 9.99])
stock = np.array([40, 15, 60, 100, 8, 33])

# 2. Add a flat $2 delivery surcharge to prices -> prices_with_delivery
prices_with_delivery = prices + 2.0
prices_with_delivery
# 4. Total value of stock on hand per product (prices * stock) -> stock_value
stock_value = prices * stock
stock_value

# 5. Apply a 20% discount to prices, rounded to 2 decimals -> discounted_prices
discounted_prices = np.round((prices * 0.8), 2)
discounted_prices

array([ 2.8 ,  9.6 ,  5.8 ,  1.44, 20.  ,  7.99])

## Exercise 4 — Aggregation & Sorting
*(covers: arrayAggregation, sortingArray)*

Using `sales_by_week` from Exercise 1 (2×5 array: 2 weeks × 5 weekdays):

1. Find total sales for each week (`.sum(axis=1)`).
2. Find total sales for each weekday across both weeks (`.sum(axis=0)`).
3. Find the overall mean, median, and 90th percentile of `sales_by_week` (`np.median`, `np.percentile`).
4. Find the unique values in `stock_grid` from Exercise 1.
5. Sort `prices` from Exercise 3 ascending, then slice out the 2 cheapest and 2 most expensive.

In [ ]:
# 1. Total sales per week (axis=1)
sales_by_week.sum(axis=1)

# 2. Total sales per weekday across both weeks (axis=0)
sales_by_week.sum(axis=0)

# 3. Overall mean, median, and 90th percentile of sales_by_week
sales_by_week.mean()
np.median(sales_by_week)
np.percentile(sales_by_week, 90)
# 4. Unique values in stock_grid
np.unique(stock_grid)

# 5. Sort prices ascending, then find 2 cheapest and 2 most expensive
prices.sort()
prices[:2]
prices[-2:]

array([12., 25.])