# NumPy Practice Exercises — Round 2

Same skills as `1.numpyExercises.ipynb`, new story: a small home gym app called **FitTrack** that logs workouts with NumPy.

Work through the exercises **in order** — later exercises reuse arrays you create in earlier ones. No data files needed, just run the setup cell below first.

In [1]:
import numpy as np

## Exercise 1 — Creating Arrays & Random Numbers
*(covers: arrayBasics, randomNumber)*

1. Create a numpy array called `pushup_reps` from the list below.
2. Print its `ndim`, `shape`, `size`, and `dtype`.
3. Reshape `pushup_reps` into a 2×4 array called `reps_by_week` (2 weeks × 4 sessions per week) — don't overwrite `pushup_reps`, save it as a new variable.
4. Create a random generator with `np.random.default_rng(7)`, then use `rng.integers(5, 51, 12)` to get 12 random lifted weights (kg). Reshape them into a 3×4 array called `weight_grid` (3 exercises × 4 sessions each).

In [7]:
# Given data
pushup_reps_list = [20, 25, 18, 30, 22, 28, 15, 35]

# 1. Create a numpy array called `pushup_reps` from pushup_reps_list
pushup_reps = np.array(pushup_reps_list)

# 2. Print ndim, shape, size, and dtype of pushup_reps
pushup_reps.ndim
pushup_reps.shape
pushup_reps.size
pushup_reps.dtype
# 3. Reshape pushup_reps into a 2x4 array called reps_by_week
reps_by_week = pushup_reps.reshape(2, 4)
reps_by_week

# 4. Create rng = np.random.default_rng(7), generate 12 random ints (5-50) with rng.integers(5, 51, 12),
#    then reshape into a 3x4 array called weight_grid
rng = np.random.default_rng(7)
weight_grid = rng.integers(5, 51, 12).reshape(3, 4)
weight_grid

array([[48, 33, 36, 46],
       [31, 40, 43, 15],
       [ 7, 18, 18, 45]])

## Exercise 2 — Indexing, Slicing & Filtering
*(covers: indexingAndSlicing, filteringArray)*

Using `weight_grid` from Exercise 1:

1. Get the full row of weights for exercise 2 (row index 1).
2. Get the weights for session column 0 across all exercises.
3. Get the single value for exercise 1 (row 0), session 3 (column 2).
4. Use a boolean mask to pull out every weight below 20kg ("light").
5. Use `np.where()` to build a same-shaped array called `weight_status` showing `"light"` where weight < 20, and `"heavy"` everywhere else.

In [16]:
# 1. Full row for exercise 2 (row index 1)
weight_grid[1]

# 2. Column 0 across all exercises
weight_grid[:, 0]

# 3. Single value: exercise 1 (row 0), session 3 (column 2)
weight_grid[0, 2]

# 4. Boolean mask: weights below 20kg
weight_grid[weight_grid < 20]

# 5. np.where() to build weight_status ("light" / "heavy")
weight_status = np.where(weight_grid < 20, "light", "heavy")
weight_status

array([['heavy', 'heavy', 'heavy', 'heavy'],
       ['heavy', 'heavy', 'heavy', 'light'],
       ['light', 'light', 'light', 'heavy']], dtype='<U5')

## Exercise 3 — Array Operations & Broadcasting
*(covers: arrayOperations, broadcasting)*

1. Create `calories_per_rep = np.array([0.5, 0.8, 0.3, 1.2, 0.6, 0.9])` (one value per exercise).
2. Add a flat 5-calorie warm-up bonus to every value using broadcasting → store as `calories_with_warmup`.
3. Create `reps_done = np.array([30, 20, 40, 15, 25, 18])` (matching order to `calories_per_rep`).
4. Calculate the total calories burned per exercise (`calories_per_rep * reps_done`) → store as `calories_burned`.
5. Apply a 10% "intensity boost" to `calories_per_rep` (multiply by 1.1) and round to 2 decimals → store as `boosted_calories`.

In [22]:
calories_per_rep = np.array([0.5, 0.8, 0.3, 1.2, 0.6, 0.9])
reps_done = np.array([30, 20, 40, 15, 25, 18])

# 2. Add a flat 5-calorie warm-up bonus to calories_per_rep -> calories_with_warmup
calories_with_warmup = calories_per_rep + 5
calories_with_warmup
# 4. Total calories burned per exercise (calories_per_rep * reps_done) -> calories_burned
calories_burned = calories_per_rep * reps_done
calories_burned
# 5. Apply a 10% intensity boost to calories_per_rep, rounded to 2 decimals -> boosted_calories
boosted_calories = np.round((calories_per_rep * 1.1), 2)
boosted_calories

array([0.55, 0.88, 0.33, 1.32, 0.66, 0.99])

## Exercise 4 — Aggregation & Sorting
*(covers: arrayAggregation, sortingArray)*

Using `reps_by_week` from Exercise 1 (2×4 array: 2 weeks × 4 sessions):

1. Find total reps for each week (`.sum(axis=1)`).
2. Find total reps for each session across both weeks (`.sum(axis=0)`).
3. Find the overall mean, median, and 90th percentile of `reps_by_week` (`np.median`, `np.percentile`).
4. Find the unique values in `weight_grid` from Exercise 1.
5. Sort `calories_per_rep` from Exercise 3 ascending, then slice out the 2 lowest and 2 highest.

In [38]:
# 1. Total reps per week (axis=1)
reps_by_week.sum(axis=1)

# 2. Total reps per session across both weeks (axis=0)
reps_by_week.sum(axis=0)

# 3. Overall mean, median, and 90th percentile of reps_by_week
reps_by_week.mean()
np.median(reps_by_week)
np.percentile(reps_by_week, 90)
# 4. Unique values in weight_grid
np.unique(weight_grid)

# 5. Sort calories_per_rep ascending, then find the 2 lowest and 2 highest
calories_per_rep.sort()
calories_per_rep[:2]
calories_per_rep[-2:]

array([0.9, 1.2])