In [6]:
import numpy as np

my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [2]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
even_odd = np.array(['even', 'odd'] * 10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [4]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [8]:
my_array[even_odd != 'odd'] = 0
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [12]:
#where() function
#   np.where(logical test, value if True, value if False)
inventory_array = np.array([12, 102, 18, 0, 0])
product_array = np.array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'])

np.where(inventory_array <= 0, 'out of stock', 'in stock')

array(['in stock', 'in stock', 'in stock', 'out of stock', 'out of stock'],
      dtype='<U12')

In [11]:
np.where(inventory_array <= 0, 'Out Of Stock', product_array)

array(['fruits', 'vegetables', 'cereal', 'Out Of Stock', 'Out Of Stock'],
      dtype='<U12')

In [13]:
np.where(my_array % 2 == 0, 'even', np.where(my_array % 3 == 0, 'divi3', my_array))

array(['even', '1', 'even', 'divi3', 'even', '5', 'even', '7', 'even',
       'divi3', 'even', '11', 'even', '13', 'even', 'divi3', 'even', '17',
       'even', '19'], dtype='<U21')

In [15]:
#ASSIGNMENT
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
products = np.array(["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"])

In [16]:
products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [24]:
mask = (prices > 25) | (products == "cola")
fancy_feast_special = products[mask]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [26]:
shipping_cost = np.where(prices > 20, 0, 5)
shipping_cost

array([5, 5, 0, 0, 5, 0])