In [6]:
import numpy as np

rng = np.random.default_rng(12345)

randomArray = (rng.random(10) * 10).reshape(2, 5)
randomArray

array([[2.27336022, 3.1675834 , 7.97365457, 6.76254671, 3.91109551],
       [3.32813928, 5.98308754, 1.86734186, 6.72756044, 9.41802865]])

In [7]:
randomArray.sum(axis=0)

array([ 5.6014995 ,  9.15067093,  9.84099643, 13.49010715, 13.32912416])

In [8]:
randomArray.sum()

np.float64(51.412398172043865)

In [13]:
print(np.median(randomArray)) #return median of array
print(np.percentile(randomArray, 80)) #return a value in the n^th percentile in an array
print(np.unique(randomArray)) #return the unique values in an array
print(np.sqrt(randomArray)) #return the square root of each value in an array

4.947091520945494
7.0047682806732645
[1.86734186 2.27336022 3.1675834  3.32813928 3.91109551 5.98308754
 6.72756044 6.76254671 7.97365457 9.41802865]
[[1.50776663 1.7797706  2.82376603 2.60048971 1.97764898]
 [1.82431885 2.44603506 1.36650717 2.59375412 3.06888068]]
