In [8]:
import numpy as np

rng = np.random.default_rng(12345)

sales_array = rng.integers(0, 100, size=(2, 5))
sales_array

array([[69, 22, 78, 31, 20],
       [79, 64, 67, 98, 39]])

In [ ]:
sales_array.sort() # sort row by row (axis = 1 by default)
sales_array

array([[20, 22, 31, 69, 78],
       [39, 64, 67, 79, 98]])

In [ ]:
sales_array.sort(axis=0) #sort by columns
sales_array

array([[20, 22, 31, 69, 78],
       [39, 64, 67, 79, 98]])

In [ ]:
#EXCERCISE
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

prices.sort()
top3 = prices[-3::]
top3

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

In [21]:
print(f"mean: {top3.mean()}")
print(f"min: {top3.min()}")
print(f"max: {top3.max()}")
print(f"median: {np.median(top3)}")


mean: 57.49
min: 22.49
max: 99.99
median: 49.99


In [20]:
print(np.unique(price_tiers))

['budget' 'luxury' 'mid-tier']
