In [8]:
import numpy as np

rng = np.random.default_rng(12345)

sales_array = rng.integers(0, 100, size=(2, 5))
sales_array

array([[69, 22, 78, 31, 20],
       [79, 64, 67, 98, 39]])

In [ ]:
sales_array.sort() # sort row by row (axis = 1 by default)
sales_array

array([[20, 22, 31, 69, 78],
       [39, 64, 67, 79, 98]])

In [ ]:
sales_array.sort(axis=0) #sort by columns
sales_array

array([[20, 22, 31, 69, 78],
       [39, 64, 67, 79, 98]])